### ISSUE TITLE
Thanks worked

### ISSUE THREAD

**Issue by Creatish** [CorneliousJD/flux_led#1]
Thanks very much this worked for me also!

Can you submit to HA so it can be updated to the release? thanks

**Comment by CorneliousJD** [comment]
Glad to hear this worked for you!

Unfortuantely because this only fixes SOME bulbs and SOME firmware versions, HA wont accept it into core, others have already tried by fixing certain bulbs, so I'm not even going to bother submitting this unfortuantely. If you find others that have problems feel free to direct them here to see if this fixes it for them too!

Thanks!
