### ISSUE TITLE
apply fix for selected led controller

### ISSUE THREAD

**Issue by Floppik** [CorneliousJD/flux_led#14]
Can i apply this fix for only controller with v8 version? Other magic home controllers work like a charm out of box. If i apply this fix, other contollers stop working right - did not turn on by automatiation or stop working.

**Comment by CorneliousJD** [comment]
My answer to this is "maybe" - you'd have to change the integration name to be something else and call it separately, so it would certainly involve some work on your end. Otherwise this just overwrites the internal flux_led. 

That way you could have flux_led and flux_led_v8 or something and have each one operate independently?
